version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: dp_management_db_dev
    restart: unless-stopped
    env_file:
      - .env.db
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_dev_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dp_network
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_dev_data:
    driver: local

networks:
  dp_network:
    external: true
